blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/crutchcorn/houseform/discussions
    about: Ask questions and discuss with other community members
